name: chat.znueni.app Static Web Apps CI/CD

on:
  push:
    branches:
      - master
    paths:
        - 'src/**'
        - 'public/**'
  workflow_dispatch:
  
jobs:
  build_and_deploy_app:
    runs-on: ubuntu-latest
    name: Build React App
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
    - name: npm ci, build and test
      run: |
        npm ci
        npm run build --if-present
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --overwrite true --auth-mode key -d '$web' -s ./build
 
  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()